<?php

return [
'ENC_KEY' =>   env('GATEWAY_ENC_KEY'),
'SECURE_SECRET'=> env('GATEWAY_SECURE_SECRET'),
'VERSION'=> env('GATEWAY_VERSION'),
'PASSCODE'=> env('GATEWAY_PASSCODE'),
'MERCHANTID'=>env('GATEWAY_MERCHANTID'),
'BANKID'=> env('GATEWAY_BANKID'),
'TERMINALID'=> env('GATEWAY_TERMINALID'),
'MCC'=>env('GATEWAY_MCC'),
'GATEWAYURL'=> env('GATEWAY_GATEWAYURL'),
'STATUSURL'=> env('GATEWAY_STATUSURL'),
'REFUNDURL'=> env('GATEWAY_REFUNDURL'),
'RETURNURL'=> env('GATEWAY_RETURNURL'),
];

